stages:

  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/tweets.csv
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed
      - params.yaml
    params:
      - vectorizer.max_features
      - vectorizer.ngram_min
      - vectorizer.ngram_max
    outs:
      - data/features
      - vectorizer.pkl

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/features/train_bow.csv
      - params.yaml
    params:
      - model.n_estimators
    outs:
      - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - model.pkl
      - data/features/test_bow.csv
    metrics:
      - metrics.json
